name: TrMenu
main: me.arasple.mc.trmenu.modules.internal.boot.PluginBoot
version: ${version}

authors:
  - Arasple
  - Bkm016

api-version: 1.13

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}

github: https://github.com/TrMenu/TrMenu
description: Modern & Advanced Menu-Plugin for Minecraft Servers
license: https://github.com/TrMenu/TrMenu/blob/v2/LICENSE.md

softdepend:
  - PlaceholderAPI
  - Vault
  - CMI
  - Cronus
  - PlayerPoints
  - HeadDatabase
  - Oraxen
  - SkinsRestorer
  - TokenManager